# Generated by Django 4.2.4 on 2024-02-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_room_name_alter_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follow_each_other',
            field=models.BooleanField(default=False),
        ),
    ]
